# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: pwd
      run: |
        $pwd
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pygame pyinstaller
    - name: pyinstaller
      run: |
        pyinstaller --onefile --noconsole main.py

    - name: ls
      run: |
        ls
        ls dist\

    - name: Upload artifact
      if: $ {{ matrix.os == "windows-latest" }}
      uses: actions/upload-artifact@v4
      with:
        name: windows_file
        path: dist/main.exe

    - name: Upload artifact
      if: $ {{ matrix.os == "macos-latest" }}
      uses: actions/upload-artifact@v4
      with:
        name: mac_file
        path: dist/main.app
